version: "3"
services:
  social:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: social
    container_name: social_container
    env_file:
      - .env.docker
    networks:
      - backend
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: bot
    container_name: bot_container
    env_file:
      - .env.docker
    depends_on:
      - social
    networks:
      - backend

networks:
  backend:
